# Each new term in the Fibonacci sequence is generated by adding
# the previous two terms. By starting with 1 and 2, the first 10
# terms will be:
# 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values
# do not exceed four million, find the sum of the even-valued terms.

def sum_even_fibonnaci_number(num):
    total_sum = 1
    fibonnaci_sequence = []
    total_sum_even_fib = 0

    while total_sum < num:
        if len(fibonnaci_sequence) < 2:
            fibonnaci_sequence.append(total_sum)
            total_sum+=total_sum
        else:
            total_sum += fibonnaci_sequence[-2]

        fibonnaci_sequence.append(total_sum)

        if total_sum % 2 == 0:
            total_sum_even_fib += total_sum      
    return total_sum_even_fib

print(sum_even_fibonnaci_number(4000000))

            